= Домашно 1: Масив и стек
:toc: left
:toc-title: Съдържание
:source-highlighter: highlightjs


== Условие

Напишете функция, която получава израз съдържащ скоби и проверява дали те са коректно организирани. По-конкретно, дефиницията за коректен израз е както следва:

* Всеки израз, който не съдържа нито една скоба е коректен (в частност и празният израз е коректен).
* Ако `X` е коректен израз, то и `(X)` е коректен израз.
* Ако `X` е коректен израз, то и `[X]` е коректен израз.
* Ако `X` е коректен израз, то и `{X}` е коректен израз.
* Ако `X` и `Y` са коректни изрази, то и `XY` е коректен израз.
* Няма други коректни изрази.

Например следните изрази са коректни:

    abc
    (abc)
    (((abc)))
    ([abc])
    ((abc){abc}(((def)))def)
    ()
    ((()))
    {}[](){}[]()
    (()()()()()()())

Докато следните НЕ СА коректни:

    (abc
    (((abc))
    abc)
    (abc))
    (
    )
    {abc]
    (abcdef[)]

Функцията да има следния прототип:

[source,cpp]
----
bool isCorrect(const char* expression)
----

В решението си можете да използвате https://en.cppreference.com/w/cpp/container/stack[`std::stack`] от STL.

Ако е нужно, добавете помощни функции, с които да решите задачата. Препоръчваме да ги покриете с unit test-ове.

== Указания за оформяне и предаване

За домашното е предоставен шаблон, в който да попълните решението си. Можете да го намерите в директорията link:template/[`template/`].

Шаблонът е под формата на CMake проект, в който ще намерите и unit test-ове, които проверяват дали предаденото от вас решение е коректно. Възможно е Unit test-овете да не покриват всички възможни случаи. Допълнете ги ако се досетите за други неща, които трябва да се проверят.

Решението си трябва да предадете в съответното задание в Moodle. Качете го архивирано в един ZIP файл. Моля, НЕ СЛАГАЙТЕ в архива временните файлове генерирани от IDE-то, компилатора и т.н. Предайте само това, което е нужно, за да се изгради и тества решението – изходният код, проектните файлове, ресурсни файлове (ако има такива) и т.н.

TIP: Би трябвало архивът да е с размер по-малък от 1MB, даже много по-малко (за тази задача вероятно ще е от порядъка на килобайти). Ако предавате архив с голям обем (например 30MB), със сигурност в архива сте включили излишни неща.